name: cpp_matrix CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: sudo apt install g++ pkg-config valgrind cppcheck clang-format lcov 
    - name: lib
      run: cd src/; make matrix_oop.a
    
  
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: sudo apt install g++ pkg-config cppcheck libgtest-dev libgmock-dev libtbb-dev valgrind clang-format
    - name: linter
      run: cd src; make check
    - name: test
      run: cd src; make test
  
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v3
    - name: report
      run: make gcov_report
